### ISSUE TITLE
[BACKEND] Configuração do Banco de Dados

### ISSUE THREAD

**Issue by Victor-Saraiva-P** [ES-Project-2024-2/Gestao-de-gastos-pessoais#26]
### 🎯 Descrição
Vou implementar com o docker acho que é opção pra deixar nosso trabalho mais fácil

**Comment by Victor-Saraiva-P** [comment]
@ES-Project-2024-2/backend-team to configurando e tava pensando em usar o dock para fazer a conexão com o DB, é dboa eu colocar o docker-compose.yml no repositório? eu coloco coisas como senha e nome de usuário para o banco num .env

**Comment by Victor-Saraiva-P** [comment]
aqui o docker que to utilizando:
```
services:
  postgres:
    image: postgres:latest
    container_name: gestorfinanceiro_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gestorfinanceiro_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s

  adminer:
    image: adminer:latest
    container_name: gestorfinanceiro_adminer
    restart: always
    ports:
      - "8888:8080"
    networks:
      - gestorfinanceiro_network
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:

networks:
  gestorfinanceiro_network:
    driver: bridge
```
